# Makefile for MO-P contest environment
# (c) 2008 Martin Mares <mj@ucw.cz>

DIRS+=mop/score
PROGS+=$(addprefix $(o)/mop/score/,mo-score-mop mo-score-mop-formatted)

$(o)/mop/score/mo-score-mop-formatted: mop/score/mo-score-mop-formatted.sh
$(o)/mop/score/mo-score-mop: mop/score/mo-score-mop.sh
