# Makefile for MO-Eval utilities
# (c) 2008 Martin Mares <mj@ucw.cz>

DIRS+=utils
PROGS+=$(addprefix $(o)/utils/,md5crypt pedant)

$(o)/utils/md5crypt: $(o)/utils/md5crypt.o $(o)/utils/md5.o
$(o)/utils/pedant: $(o)/utils/pedant.o
